import { useEffect, useState } from "react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAppDispatch, useAppSelector } from "@/redux/hooks";
import { getProfitAndLossReportThunk } from "@/redux/report";
import ReportLayout from "@/components/reports/ReportLayout";
import ReportSummaryCards from "@/components/reports/ReportSummaryCards";

const ProfitAndLoss = () => { const dispatch = useAppDispatch(); const { profitAndLossReport: report } = useAppSelector((state) => state.report); const [filters, setFilters] = useState({ fromDate: "", toDate: "" }); useEffect(() => { dispatch(getProfitAndLossReportThunk(filters)); }, [dispatch, filters]); const rows = [["Booking Revenue", report?.totalRevenue], ["Vehicle Expense", report?.vehicleExpense], ["Office Expense", report?.officeExpense], ["Salary Expense", report?.salaryExpense], ["Diesel Expense", report?.dieselExpense], ["Total Expense", report?.totalExpense], ["Net Profit", report?.netProfit]]; return <ReportLayout title="Profit & Loss" description="Actual collections less business expenses"><div className="space-y-5 p-4"><div className="grid gap-4 md:grid-cols-3"><div><Label>From Date</Label><Input type="date" value={filters.fromDate} onChange={(event) => setFilters((value) => ({ ...value, fromDate: event.target.value }))} /></div><div><Label>To Date</Label><Input type="date" value={filters.toDate} onChange={(event) => setFilters((value) => ({ ...value, toDate: event.target.value }))} /></div></div><ReportSummaryCards items={[{ title: "Revenue", value: report?.totalRevenue || 0, prefix: "₹", icon: <span />, color: "bg-gradient-to-r from-green-500 to-emerald-600" }, { title: "Total Expense", value: report?.totalExpense || 0, prefix: "₹", icon: <span />, color: "bg-gradient-to-r from-orange-500 to-red-500" }, { title: "Net Profit", value: report?.netProfit || 0, prefix: "₹", icon: <span />, color: "bg-gradient-to-r from-blue-500 to-cyan-500" }]} /><div className="rounded-lg border"><table className="w-full"><tbody>{rows.map(([label, amount]) => <tr key={String(label)} className="border-b last:border-0"><td className="p-4">{label}</td><td className="p-4 text-right font-semibold">₹{Number(amount || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}</td></tr>)}</tbody></table></div></div></ReportLayout>; };
export default ProfitAndLoss;
